<?php

/**
 * @file
 * Provides a leaguegroup entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\clashofclans_api\Render;

/**
 * Implements hook_theme().
 */
function clashofclans_leaguegroup_theme() {
  return [
    'clashofclans_leaguegroup' => [
      'render element' => 'elements',
    ],

    'clashofclans_leaguegroup_currentwar' => [
      'variables' => [
        'data' => NULL,
      ],
    ],

    'clashofclans_leaguegroup_clans' => [
      'variables' => [
        'items' => NULL,
      ],
    ],

    'clashofclans_leaguegroup_rounds' => [
      'variables' => [
        'items' => NULL,
        'wars' => NULL,
      ],
    ],

  ];
}

/**
 * Prepares variables for leaguegroup templates.
 *
 * Default template: clashofclans-leaguegroup.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the leaguegroup information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_clashofclans_leaguegroup(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    if ($key == 'field_data') {
      $json = $variables['elements'][$key]['#items']->value;
      if ($json) {
        $league_group = \Drupal::service('clashofclans_leaguegroup.league_group');
        $data = \Drupal\Component\Serialization\Json::decode($json);
        $data = $league_group->processData($data);
        $renderable = [
          '#theme' => 'clashofclans_leaguegroup_currentwar',
          '#data' => $data,
          '#weight' => $variables['elements'][$key]['#weight'],
        ];
        $variables['content'][$key] = $renderable;
      }
    } else {
      $variables['content'][$key] = $variables['elements'][$key];
    }
  }
}

function template_preprocess_clashofclans_leaguegroup_clans(array &$variables) {
  $items = $variables['items'];
  $header = [
    '#',
    'badgeUrls' => ['data' => 'Badge'],
    'name' => ['data' => 'Clan'],
    // 'clanLevel' => ['data' => 'clanLevel', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
    'stars' => ['data' => t('Stars')],
    'destructionPercentage' => ['data' => '💥 %'],
  ];
  $rows = [];

  $i = 0;
  foreach ($items as $item) {
    $row = [];
    $i++;
    $row[] = $i;
    $renderable = [
      '#theme' => 'clashofclans_api__badgeUrls',
      '#data' => $item['badgeUrls'],
    ];
    $row[] = \Drupal::service('renderer')->renderPlain($renderable);

    $text = $item['name'];
    $url = \Drupal\Core\Url::fromUserInput($item['tag']);
    $link = \Drupal\Core\Link::fromTextAndUrl($text, $url);
    $row[] = $link;

    $row[] = $item['stars']. '⭐';
    $row[] = $item['destructionPercentage'];

    $rows[] = $row;
  }

  $renderable = [
    '#type' => 'table',
    // '#responsive' => FALSE,
    '#sticky' => TRUE,
    '#header' => $header,
    '#rows' => $rows,
  ];

  $variables['content'] = $renderable;

}
