<?php
use Drupal\clashofclans_api\Render;

/**
 * @file
 * Primary module hooks for ClashOfClans API module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

function clashofclans_api_theme($existing, $type, $theme, $path) {
  $items = [
    'clashofclans_api' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
  ];

  $keys = [
    'location', 'badgeUrls', 'clanPoints', 'clan', 'league', 'name',
    'warLeague', 'chatLanguage', 'labels', 'memberList', 'trophies',
    'legendStatistics', 'heroes', 'spells', 'achievements', 'troops'
  ];
  foreach ($keys as $key) {
    $id = 'clashofclans_api__'. $key;
    $items[$id] = [
      'variables' => [
        'data' => NULL,
      ],
    ];
  }


  return $items;
}

/**
 * Prepares variables for memberList templates.
 *
 * Default template: clashofclans-api--memberList.html.twig.
 *
 * @param array $variables
 *
 */
function template_preprocess_clashofclans_api__memberList(array &$variables) {
  $header = [
    'clanRank' => ['data' => '#'],
    'previousClanRank' => ['data' => 'Prev', 'class' => [RESPONSIVE_PRIORITY_LOW]],
    'league' => ['data' => 'League'],
    'expLevel' => ['data' => 'Exp', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
    'name' => ['data' => 'Name'],
    'tag' => ['data' => 'Tag', 'class' => [RESPONSIVE_PRIORITY_LOW]],
    'role' => ['data' => 'Role', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
    'donations' => ['data' => 'Donated', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
    'donationsReceived' => ['data' => 'Received', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
    'versusTrophies' => ['data' => 'Versus', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
    'trophies' => ['data' => 'Trophies'],
  ];

  $renderable = Render::table($header, $variables['data'], 'player');

  $variables['content'] = $renderable;
}

/**
 * Implements hook_local_tasks_alter().
 *
 * @inheritdoc
*/
function clashofclans_api_local_tasks_alter(&$local_tasks) {
  $local_tasks['entity.clashofclans_location.view']['title'] = t('Clans');
}
