<?php

/**
 * @file
 * Primary module hooks for ClashOfClans API module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

function clashofclans_api_theme($existing, $type, $theme, $path) {
  $items = [
    'clashofclans_api' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
  ];

  $keys = [
    'location', 'badgeUrls', 'clanPoints', 'clan', 'league', 'name',
    'warLeague', 'chatLanguage', 'labels', 'memberList', 'trophies',
    'legendStatistics', 'heroes', 'spells', 'achievements', 'troops'
  ];
  foreach ($keys as $key) {
    $id = 'clashofclans_api__'. $key;
    $items[$id] = [
      'variables' => [
        'data' => NULL,
      ],
    ];
  }


  return $items;
}

/**
 * Prepares variables for memberList templates.
 *
 * Default template: clashofclans-api--memberList.html.twig.
 *
 * @param array $variables
 *
 */
function template_preprocess_clashofclans_api__memberList(array &$variables) {
  $data = $variables['data'];
  $header = [
    'clanRank' => '#',
    'previousClanRank' => 'Prev',
    'league' => 'League',
    'expLevel' => 'Exp',
    'name' => 'Name',
    'tag' => 'Tag',
    'role' => 'Role',
    'donations' => 'Donated',
    'donationsReceived' => 'Received',
    'versusTrophies' => 'Versus',
    'trophies' => 'Trophies',
  ];
  $rows = [];
  foreach ($data as $item) {
    $row = [];
    foreach (array_keys($header) as $key) {
      if ($key == 'name' && isset($item['tag'])) {
        $link = \Drupal\Core\Link::createFromRoute($item[$key], 'clashofclans_player.tag', ['tag' => $item['tag']]);
        $renderable = $link->toRenderable();
      } else {
        $renderable = [
          '#theme' => 'clashofclans_api__'. $key,
          '#data' => $item[$key],
        ];
      }
      $row[] = \Drupal::service('renderer')->renderPlain($renderable);
    }
    $rows[] = $row;
  }

  $low = ['previousClanRank', 'tag', 'donations', 'donationsReceived', 'versusTrophies'];
  foreach ($low as $col) {
    $val = $header[$col];
    $header[$col] = [
      'data' => $val,
      'class' => [RESPONSIVE_PRIORITY_LOW],
    ];
  }

  $medium = ['league', 'expLevel'];
  foreach ($medium as $col) {
    $val = $header[$col];
    $header[$col] = [
      'data' => $val,
      'class' => [RESPONSIVE_PRIORITY_MEDIUM],
    ];
  }

  $renderable = [
    '#type' => 'table',
    // '#responsive' => FALSE,
    '#sticky' => TRUE,
    '#header' => array_values($header),
    '#rows' => $rows,
  ];
  $variables['data'] = $renderable;
}

/**
 * Implements hook_local_tasks_alter().
 *
 * @inheritdoc
*/
function clashofclans_api_local_tasks_alter(&$local_tasks) {
  $local_tasks['entity.clashofclans_location.view']['title'] = t('Clans');
}
