<?php

/**
 * @file
 * Provides a clan entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\clashofclans_clan\Clan;

/**
 * Implements hook_theme().
 */
function clashofclans_clan_theme() {
  return [
    'clashofclans_clan' => [
      'render element' => 'elements',
    ],

    'clashofclans_clan_warlog' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
  ];
}

/**
 * Prepares variables for clan templates.
 *
 * Default template: clashofclans-clan.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the clan information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_clashofclans_clan(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    if ($key == 'extra_field_clashofclans_clan_live_data' && isset($variables['elements'][$key]['#data'])) {
      $data = $variables['elements'][$key]['#data'];
      // $weight = $variables['elements'][$key]['#weight'];
      $variables['data'] = $data;
      unset($variables['elements'][$key]);
    } else {
      $variables['content'][$key] = $variables['elements'][$key];
    }
  }
  $clan = \Drupal::service('clashofclans_clan.clan');
  $variables['content']['#cache']['max-age'] = $clan->client->getMaxAge();
}

function clashofclans_clan_entity_prepare_view($entity_type_id, array $entities, array $displays, $view_mode) {

  // // Load a specific node into the user object for later theming.
  // if (!empty($entities) && $entity_type_id == 'clashofclans_clan' && $view_mode == 'full') {
  //   $clan = \Drupal::service('clashofclans_clan.clan');
  //   foreach ($entities as $entity) {
  //     $clan->prepareView($entity);
  //   }
  // }
}
