<?php
/**
 * @file
 * Provides a clan entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function clashofclans_clan_theme() {
  return [
    'clashofclans_clan' => [
      'render element' => 'elements',
    ],

    'clashofclans_clan_warlog' => [
      'variables' => [
        'data' => NULL,
      ],
    ],

    // 'clashofclans_clan_members' => [
    //   'variables' => [
    //     'items' => NULL,
    //   ],
    // ],

    'clashofclans_clan_memberlist' => [ //memberList in clan page.
      'variables' => [
        'items' => NULL,
      ],
    ],
  ];
}

/**
 * Prepares variables for clan templates.
 *
 * Default template: clashofclans-clan.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the clan information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_clashofclans_clan(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    if ($key == 'extra_field_clashofclans_clan_live_data' && isset($variables['elements'][$key]['#data'])) {
      $data = $variables['elements'][$key]['#data'];
      // $weight = $variables['elements'][$key]['#weight'];
      $variables['data'] = $data;
      unset($variables['elements'][$key]);
    } else {
      $variables['content'][$key] = $variables['elements'][$key];
    }
  }
  $clan = \Drupal::service('clashofclans_clan.clan');
  $variables['content']['#cache']['max-age'] = $clan->client->getMaxAge();
}

/**
 * Prepares variables for clan_memberlist templates.
 *
 * Default template: clashofclans-clan-memberlist.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - items
 */
function template_preprocess_clashofclans_clan_memberlist(array &$variables) {
  $items = $variables['items'];
  $header = [
    'clanRank' => ['data' => '#'],
    // 'previousClanRank' => ['data' => 'Prev', 'class' => [RESPONSIVE_PRIORITY_LOW]],
    'league' => ['data' => 'League'],
    'expLevel' => ['data' => 'Exp', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
    'name' => ['data' => 'Name'],
    'tag' => ['data' => 'Tag', 'class' => [RESPONSIVE_PRIORITY_LOW]],
    'role' => ['data' => 'Role', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
    'donations' => ['data' => 'Donated', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
    'donationsReceived' => ['data' => 'Received', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
    'versusTrophies' => ['data' => 'Versus', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
    'trophies' => ['data' => 'Trophies'],
  ];

  $variables['content'] = \Drupal\clashofclans_api\Render::table($header, $items);

}

/**
 * Prepares variables for clan_members templates.
 *
 * Default template: clashofclans-clan-members.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - items
 */
// function template_preprocess_clashofclans_clan_members(array &$variables) {
//   $header = [
//     'clanRank' => ['data' => '#'],
//     'previousClanRank' => ['data' => 'Prev', 'class' => [RESPONSIVE_PRIORITY_LOW]],
//     'league' => ['data' => 'League', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
//     'expLevel' => ['data' => 'Exp', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
//     'name' => ['data' => 'Name'],
//     // 'tag' => ['data' => 'Tag', 'class' => [RESPONSIVE_PRIORITY_LOW]],
//     // 'role' => ['data' => 'Role', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
//     // 'donations' => ['data' => 'Donated', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
//     // 'donationsReceived' => ['data' => 'Received', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
//     // 'versusTrophies' => ['data' => 'Versus', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
//     'townHallLevel' => ['data' => 'TH', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
//     'attackWins' => ['data' => 'AW'],
//     'defenseWins' => ['data' => 'DW'],
//     'legendTrophies' => ['data' => 'legendTrophies', 'class' => [RESPONSIVE_PRIORITY_LOW]],
//     'bestSeason' => ['data' => 'bestSeason', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
//     'bestRank' => ['data' => 'bestRank', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
//     'previousRank' => ['data' => 'previous', 'class' => [RESPONSIVE_PRIORITY_MEDIUM]],
//     'trophies' => ['data' => 'Trophies'],
//   ];
//
//   $renderable = [
//     '#theme' => 'clashofclans_api__table',
//     '#sticky' => TRUE,
//     '#header' => $header,
//     '#items' => $variables['items'],
//   ];
//
//   $variables['content'] = $renderable;
//
// }
