<?php

/**
 * @file
 * Provides a player entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function clashofclans_player_theme() {
  return [
    'clashofclans_player' => [
      'render element' => 'elements',
    ],

    'clashofclans_player_tag' => [
      'variables' => [
        'player' => NULL,
        'clan' => NULL,
        'pets' => NULL,
      ],
    ],
  ];
}

/**
 * Prepares variables for player templates.
 *
 * Default template: clashofclans-player.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the player information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_clashofclans_player(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for player_tag templates.
 *
 * Default template: clashofclans-player-tag.html.twig.
 *
 * @param array $variables
 */
function template_preprocess_clashofclans_player_tag(array &$variables) {
  $player = $variables['player'];
  if (isset($player['clan'])) {
    $clan = \Drupal\clashofclans_api\Render::link($player['clan']['name'], $player['clan']['tag'], 'clan');
    $variables['clan'] = $clan;
  }

  if (isset($player['troops'])) {
    $pets = [];
    $names = ['L.A.S.S.I', 'Mighty Yak', 'Electro Owl', 'Unicorn'];
    foreach ($player['troops'] as $troop) {
      if (in_array($troop['name'], $names)) {
        $pets[] = $troop;
      }
    }
    $variables['pets'] = $pets;
  }


  // dpm($player['troops']);
}
