<?php

/**
 * @file
 * Provides a location entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function clashofclans_location_theme() {
  return [
    'clashofclans_location' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for location templates.
 *
 * Default template: clashofclans-location.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the location information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_clashofclans_location(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
