clashofclans_war.clashofclans_war_type.*:
  type: config_entity
  label: 'War type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
