<?php

/**
 * @file
 * Provides a war entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function clashofclans_war_theme() {
  return [
    'clashofclans_war' => [
      'render element' => 'elements',
    ],

    'clashofclans_war_data' => [
      'variables' => [
        'data' => NULL,
      ],
    ],

  ];
}

/**
 * Prepares variables for war templates.
 *
 * Default template: clashofclans-war.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the war information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_clashofclans_war(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    if ($key == 'data') {
      $weight = $variables['elements'][$key]['#weight'];
      $json = $variables['elements'][$key]['#items']->getString();
      $data = \Drupal\Component\Serialization\Json::decode($json);
      $build = [
        '#theme' => 'clashofclans_war_data',
        '#data' => $data,
        '#weight' => $weight,
      ];
      $variables['content']['data'] = $build;
    } else {
      $variables['content'][$key] = $variables['elements'][$key];
    }
  }
}
